# Generated by Django 5.2.1 on 2025-05-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
