# Generated by Django 5.2.1 on 2025-05-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
