# Generated by Django 5.2.1 on 2025-05-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_remove_orderitem_order_delete_order_delete_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
                ('available', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('fee', models.IntegerField()),
                ('counter', models.IntegerField()),
                ('counter_price', models.IntegerField()),
                ('cover', models.URLField()),
            ],
        ),
    ]
