# Generated by Django 5.2.1 on 2025-05-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_orderedbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedBook',
        ),
    ]
