# Generated by Django 5.2.1 on 2025-05-20 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_orderedbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('writer', models.CharField(max_length=255)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validation', models.IntegerField(help_text='Validation period in days')),
                ('item', models.IntegerField(default=1)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PopularBook', to='bookstore.category')),
            ],
        ),
    ]
